# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0014_feedback_to_comparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('media_url', models.TextField(db_index=True, verbose_name='media url')),
                ('environment_id', models.TextField(db_index=True, verbose_name='environment id')),
                ('clip_tracking_id', models.IntegerField(db_index=True, verbose_name='clip tracking id')),
                ('source', models.TextField(blank=True, default='', verbose_name='note of where the clip came from')),
            ],
        ),
    ]
