# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0015_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_red', models.BooleanField()),
                ('bound_clips', models.ManyToManyField(related_name='tree_bindings', to='human_feedback_api.Clip')),
                ('left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='human_feedback_api.SortTree')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='human_feedback_api.SortTree')),
                ('pending_clips', models.ManyToManyField(related_name='pending_sort_locations', to='human_feedback_api.Clip')),
                ('right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='human_feedback_api.SortTree')),
            ],
        ),
    ]
