# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0017_sorttree_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='tree_node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_feedback_api.SortTree'),
        ),
    ]
