# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0018_comparison_tree_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='tree_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_feedback_api.SortTree'),
        ),
    ]
