# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0019_auto_20170824_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='relevant_to_pending_clip',
            field=models.BooleanField(default=False),
        ),
    ]
